name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [develop]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: checout
        uses: actions/checout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}

      - name: npm install 
        run: npm install 

      - name: npm run build-prod 
        run: npm run build-prod 

  